import type { Laptop } from "@shared/types";

export const CATALOG_VERSION = "2026.09-curated-inr-v2";

export const laptops: Laptop[] = [
  {
    id: 1,
    brand: "Lenovo",
    model: "Yoga Pro 7i",
    slug: "lenovo-yoga-pro-7i",
    tagline: "Quiet power for code, creation, and everyday carry",
    price: 89990,
    currency: "INR",
    cpu: "Intel Core Ultra 7 155H",
    cpuScore: 88,
    gpu: "NVIDIA GeForce RTX 4050 6GB",
    gpuScore: 76,
    ram: 32,
    storage: 1000,
    storageType: "NVMe SSD",
    display: "14.5\" 3K OLED",
    displaySize: 14.5,
    resolution: "3072 × 1920",
    refreshRate: 120,
    battery: "73 Wh",
    batteryScore: 86,
    weight: 1.49,
    gamingScore: 74,
    programmingScore: 94,
    editingScore: 88,
    aiScore: 82,
    buildScore: 91,
    valueScore: 86,
    vram: 6,
    colors: { from: "#f2c94c", to: "#f2994a", accent: "#151515" },
    source: "LaptopAI curated benchmark set",
    updatedAt: "2026-09-01",
  },
  {
    id: 2,
    brand: "ASUS",
    model: "ROG Zephyrus G14",
    slug: "asus-rog-zephyrus-g14",
    tagline: "A compact gaming rig with creator-grade speed",
    price: 109990,
    currency: "INR",
    cpu: "AMD Ryzen 9 8945HS",
    cpuScore: 94,
    gpu: "NVIDIA GeForce RTX 4060 8GB",
    gpuScore: 91,
    ram: 32,
    storage: 1000,
    storageType: "NVMe SSD",
    display: "14\" 3K OLED",
    displaySize: 14,
    resolution: "2880 × 1800",
    refreshRate: 120,
    battery: "73 Wh",
    batteryScore: 80,
    weight: 1.68,
    gamingScore: 94,
    programmingScore: 92,
    editingScore: 95,
    aiScore: 92,
    buildScore: 92,
    valueScore: 82,
    vram: 8,
    colors: { from: "#ff6b5e", to: "#7b61ff", accent: "#ffffff" },
    source: "LaptopAI curated benchmark set",
    updatedAt: "2026-09-01",
  },
  {
    id: 3,
    brand: "Apple",
    model: "MacBook Air 15",
    slug: "apple-macbook-air-15",
    tagline: "Distraction-free battery life in a spacious frame",
    price: 104900,
    currency: "INR",
    cpu: "Apple M3",
    cpuScore: 86,
    gpu: "Integrated 10-core GPU",
    gpuScore: 63,
    ram: 16,
    storage: 512,
    storageType: "SSD",
    display: "15.3\" Liquid Retina",
    displaySize: 15.3,
    resolution: "2880 × 1864",
    refreshRate: 60,
    battery: "66.5 Wh",
    batteryScore: 98,
    weight: 1.51,
    gamingScore: 52,
    programmingScore: 91,
    editingScore: 82,
    aiScore: 64,
    buildScore: 97,
    valueScore: 79,
    colors: { from: "#d6e5ea", to: "#92a8d1", accent: "#17212b" },
    source: "LaptopAI curated benchmark set",
    updatedAt: "2026-09-01",
  },
  {
    id: 4,
    brand: "Acer",
    model: "Swift Go 14",
    slug: "acer-swift-go-14",
    tagline: "An efficient, bright-screen everyday workhorse",
    price: 67990,
    currency: "INR",
    cpu: "Intel Core Ultra 5 125H",
    cpuScore: 78,
    gpu: "Intel Arc integrated graphics",
    gpuScore: 48,
    ram: 16,
    storage: 512,
    storageType: "NVMe SSD",
    display: "14\" 2.8K OLED",
    displaySize: 14,
    resolution: "2880 × 1800",
    refreshRate: 90,
    battery: "65 Wh",
    batteryScore: 84,
    weight: 1.32,
    gamingScore: 42,
    programmingScore: 83,
    editingScore: 68,
    aiScore: 61,
    buildScore: 78,
    valueScore: 94,
    colors: { from: "#d4f1f4", to: "#75e6da", accent: "#083344" },
    source: "LaptopAI curated benchmark set",
    updatedAt: "2026-09-01",
  },
  {
    id: 5,
    brand: "HP",
    model: "Omen 16",
    slug: "hp-omen-16",
    tagline: "Desktop-class graphics for serious play and rendering",
    price: 94990,
    currency: "INR",
    cpu: "AMD Ryzen 7 8845HS",
    cpuScore: 90,
    gpu: "NVIDIA GeForce RTX 4060 8GB",
    gpuScore: 92,
    ram: 16,
    storage: 1000,
    storageType: "NVMe SSD",
    display: "16.1\" QHD IPS",
    displaySize: 16.1,
    resolution: "2560 × 1440",
    refreshRate: 165,
    battery: "83 Wh",
    batteryScore: 72,
    weight: 2.33,
    gamingScore: 96,
    programmingScore: 82,
    editingScore: 90,
    aiScore: 89,
    buildScore: 83,
    valueScore: 90,
    vram: 8,
    colors: { from: "#29323c", to: "#485563", accent: "#f5f3ee" },
    source: "LaptopAI curated benchmark set",
    updatedAt: "2026-09-01",
  },
  {
    id: 6,
    brand: "Dell",
    model: "XPS 14",
    slug: "dell-xps-14",
    tagline: "Premium materials and a sharp display for focused work",
    price: 129990,
    currency: "INR",
    cpu: "Intel Core Ultra 7 155H",
    cpuScore: 88,
    gpu: "NVIDIA GeForce RTX 4050 6GB",
    gpuScore: 76,
    ram: 32,
    storage: 1000,
    storageType: "NVMe SSD",
    display: "14.5\" 3.2K OLED",
    displaySize: 14.5,
    resolution: "3200 × 2000",
    refreshRate: 120,
    battery: "69.5 Wh",
    batteryScore: 84,
    weight: 1.68,
    gamingScore: 70,
    programmingScore: 91,
    editingScore: 90,
    aiScore: 80,
    buildScore: 96,
    valueScore: 70,
    vram: 6,
    colors: { from: "#eee8df", to: "#c9d6ff", accent: "#202124" },
    source: "LaptopAI curated benchmark set",
    updatedAt: "2026-09-01",
  },
  {
    id: 7,
    brand: "ASUS",
    model: "TUF Gaming A15",
    slug: "asus-tuf-gaming-a15",
    tagline: "The value pick for high-FPS gaming and upgrades",
    price: 74990,
    currency: "INR",
    cpu: "AMD Ryzen 7 7735HS",
    cpuScore: 82,
    gpu: "NVIDIA GeForce RTX 4060 8GB",
    gpuScore: 90,
    ram: 16,
    storage: 512,
    storageType: "NVMe SSD",
    display: "15.6\" FHD IPS",
    displaySize: 15.6,
    resolution: "1920 × 1080",
    refreshRate: 144,
    battery: "90 Wh",
    batteryScore: 75,
    weight: 2.2,
    gamingScore: 93,
    programmingScore: 76,
    editingScore: 78,
    aiScore: 86,
    buildScore: 80,
    valueScore: 96,
    vram: 8,
    colors: { from: "#18181b", to: "#27272a", accent: "#facc15" },
    source: "LaptopAI curated benchmark set",
    updatedAt: "2026-09-01",
  },
  {
    id: 8,
    brand: "Lenovo",
    model: "ThinkPad E14 Gen 6",
    slug: "lenovo-thinkpad-e14-gen-6",
    tagline: "A practical keyboard-first machine for developers",
    price: 71990,
    currency: "INR",
    cpu: "AMD Ryzen 7 7735U",
    cpuScore: 80,
    gpu: "AMD Radeon 680M integrated",
    gpuScore: 46,
    ram: 16,
    storage: 512,
    storageType: "NVMe SSD",
    display: "14\" WUXGA IPS",
    displaySize: 14,
    resolution: "1920 × 1200",
    refreshRate: 60,
    battery: "57 Wh",
    batteryScore: 77,
    weight: 1.44,
    gamingScore: 35,
    programmingScore: 95,
    editingScore: 62,
    aiScore: 54,
    buildScore: 91,
    valueScore: 91,
    colors: { from: "#e6edf3", to: "#b8c6db", accent: "#0f172a" },
    source: "LaptopAI curated benchmark set",
    updatedAt: "2026-09-01",
  },
  {
    id: 9,
    brand: "Acer",
    model: "Nitro V 15",
    slug: "acer-nitro-v-15",
    tagline: "Dedicated graphics for affordable high-FPS play",
    price: 69990,
    currency: "INR",
    cpu: "Intel Core i5-13420H",
    cpuScore: 76,
    gpu: "NVIDIA GeForce RTX 4050 6GB",
    gpuScore: 78,
    ram: 16,
    storage: 512,
    storageType: "NVMe SSD",
    display: "15.6\" FHD IPS",
    displaySize: 15.6,
    resolution: "1920 × 1080",
    refreshRate: 144,
    battery: "57.5 Wh",
    batteryScore: 66,
    weight: 2.1,
    gamingScore: 86,
    programmingScore: 71,
    editingScore: 74,
    aiScore: 76,
    buildScore: 75,
    valueScore: 92,
    vram: 6,
    colors: { from: "#253b5e", to: "#1f2937", accent: "#fbbf24" },
    source: "LaptopAI curated benchmark set",
    updatedAt: "2026-09-01",
  },
];

export function getLaptop(id: number) {
  return laptops.find((laptop) => laptop.id === id);
}
